f.setWidth 500 height 500 backgroundColour "#dddddd"
f.setTitle "Test Script"

#platform.writeToFile "test.txt" value "hello world"

NOT_INITED = testIf __INIT isnot 1
__INIT = @ 1

#(NOT_INITED) f.doAction "setOrientation" args "portrait" onDoneGoto :CONT

:CONT
f.doAction "setScaleMode" args "normal" onDoneGoto :SCALED

:SCALED
f.loadResource "#test.map" as "test"

H = @ "Hello "
W = @ "world!"

HW = join H & W
(NAME) HW = join HW & " " && NAME

f.writeAs "hello_world" value HW atX 10 y 10 onClickGoto :CLICK border "#ff0000"

f.drawAs "button1" id "test.face" atX 100 y 100 onClickGoto :CLICK
f.drawAs "button2" id "test.face" atX 200 y 200 onClickGoto :CLICK

stop

:CLICK
    ID = f.getLastActionId
    f.doAction "showToast" args ID onDoneGoto :NOTHING
    stop

:NOTHING
    stop
